# Generated by Django 5.0.4 on 2024-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='About Page', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='item_images')),
                ('content', models.TextField()),
            ],
        ),
    ]
