# Generated by Django 5.0.4 on 2024-06-11 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_aboutus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutUs",
        ),
    ]
